### ISSUE TITLE
Build not working

### ISSUE THREAD

**Issue by YasasviPeruvemba** [rhysd/vim.wasm#28]
After cloning the repo and building it using ./build.sh, running a local server and hosting vim.html raises quite a few errors.

Following the steps under Development of the **README** file, raised these errors.
>
![Screenshot from 2019-05-29 15-40-33](https://user-images.githubusercontent.com/44848793/58549548-66b63d00-8229-11e9-995e-c5eff58a78e3.png)

**Vim** should run without any problems in the browser

But what I see is a blank screen with multiple errors in the console

**Your environment:**
 - OS: Ubuntu 18.04
 - Browser: Google Chrome
 - Browser Version: 74.0.3729.169

**Comment by rhysd** [comment]
It seems that `Pointer_stringify()` function was removed from the latest Emscripten. For sure, please describe emscripten version you installed.

**Comment by YasasviPeruvemba** [comment]
I currently have emscripten 1.38.16 installed. Which version was used to build this project initially?

**Comment by rhysd** [comment]
I guess it was 1.38.6 or 1.38.8.

I could reproduce this issue with 1.38.32 (the latest). I'll fix this.

**Comment by rhysd** [comment]
I fixed this issue at c84a8ed. In my environment, now it works.

**Comment by YasasviPeruvemba** [comment]
Well. thanks a lot, this error seems to have been resolved, but after building the project again, on any Key press from the keyboard, there seems to be an error with asynchronous calls made to ccall and cwrap.
Screenshot - 
![Screenshot from 2019-05-30 15-03-31](https://user-images.githubusercontent.com/44848793/58623723-400d0a80-82ec-11e9-9ba1-087e5a745468.png)

**Comment by rhysd** [comment]
Yeah, I also noticed the assertion error. There is one more assertion added to `ccall()` function at recent emscripten and it fails. It is solved by adding `{ async: true}` as last argument at `cwrap()` function call. The assertion is correct. However, after that, it still crashes with assertion error in `emterpret()`. I needs more investigation for this, but it works correctly with release build.

**Comment by YasasviPeruvemba** [comment]
The release build seems to show a memory access error on Keyboard Input from keys other than Alt,Shift and Ctrl, which I'm assuming were added as special characters to not be sent as input.
![Screenshot from 2019-05-31 16-54-03](https://user-images.githubusercontent.com/44848793/58703043-107e0100-83c5-11e9-86b7-7122ac17f907.png)

**Comment by rhysd** [comment]
That error does not occur on my environment with release build. But something would go wrong (maybe touching undefined behavior). More investigation is necessary. (This week, I would not be able to have enough time and environment to investigate this issue..)

**Comment by rhysd** [comment]
@YasasviPeruvemba 

Could you create a new issue for the memory violation?
This issue was already closed since the original error was fixed.

**Comment by rhysd** [comment]
It was fixed by #30.
